// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaMCKIKlIZw85ECRAIllO0Y1xv1FA8e48',
    appId: '1:486881316013:web:3a18ce128ab8f3904d4a24',
    messagingSenderId: '486881316013',
    projectId: 'js-weatherly-app',
    authDomain: 'js-weatherly-app.firebaseapp.com',
    storageBucket: 'js-weatherly-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_GS3znr5Ois8GvR--rZWN98BSUgI2h3E',
    appId: '1:486881316013:android:0b1d3d9d8eb18a914d4a24',
    messagingSenderId: '486881316013',
    projectId: 'js-weatherly-app',
    storageBucket: 'js-weatherly-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAXSQPySU5M-194N7z_IKIga-3rxehxVc',
    appId: '1:486881316013:ios:6a6b68b6db2cdb0d4d4a24',
    messagingSenderId: '486881316013',
    projectId: 'js-weatherly-app',
    storageBucket: 'js-weatherly-app.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAXSQPySU5M-194N7z_IKIga-3rxehxVc',
    appId: '1:486881316013:ios:6a6b68b6db2cdb0d4d4a24',
    messagingSenderId: '486881316013',
    projectId: 'js-weatherly-app',
    storageBucket: 'js-weatherly-app.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaMCKIKlIZw85ECRAIllO0Y1xv1FA8e48',
    appId: '1:486881316013:web:1c584572276049cd4d4a24',
    messagingSenderId: '486881316013',
    projectId: 'js-weatherly-app',
    authDomain: 'js-weatherly-app.firebaseapp.com',
    storageBucket: 'js-weatherly-app.firebasestorage.app',
  );
}
